### ISSUE TITLE
"filter by tag" ui is broken on windows

### ISSUE THREAD

**Issue by disjukr** [pbkit/pbkit-devtools#29]
![image](https://user-images.githubusercontent.com/690661/179764880-43862a60-ce14-4994-85b4-d9c135c5714e.png)
![image](https://user-images.githubusercontent.com/690661/179764920-b3e1575f-0806-48e1-84ef-1affdb96d8fe.png)

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

**Comment by SimYunSup** [comment]
@hyp3rflow put a code `overflow: scroll` in the style tag.
https://github.com/pbkit/pbkit-devtools/blob/3070f39678f7396dec6acbd05a6069399f79a4c3/packages/browser-extension/src/pages/index/Settings/index.tsx#L109
https://github.com/pbkit/pbkit-devtools/blob/3070f39678f7396dec6acbd05a6069399f79a4c3/packages/standalone-webview/src/pages/index/Settings/index.tsx#L109
Is there a history of this code?

**Comment by hyp3rflow** [comment]
@SimYunSup Well, I don't think there was specific reason for that line of code. Does it work well with multiple chosen tags when deleted the `overflow` property?

**Comment by SimYunSup** [comment]
No `overflow: scroll` with multiple tags, works like below.
![image](https://user-images.githubusercontent.com/47362439/195303273-a5a8de79-2bbc-4ef2-8cdc-c69f0d562f7d.png)

**Comment by SimYunSup** [comment]
@hyp3rflow If the style attr of Select changes like below, Works well like an image.
```tsx
<Select
styles={{
          container: (base) => ({ ...base, minWidth: 150 }),
          valueContainer: (base) => ({ ...base, padding: 0, display: "flex", flexWrap: "nowrap", overflow: "hidden" }),
          clearIndicator: (base) => ({ ...base, padding: 0 }),
          dropdownIndicator: (base) => ({ ...base, padding: 0 }),
          control: (base) => ({
            ...base,
            borderTop: "none",
            borderBottom: "none",
            borderRadius: 0,
            minHeight: 0,
            height: "100%",
            padding: "0 2px",
            boxShadow: "none",
            borderColor: "var(--pb-sep)",
            ":hover": {
              borderColor: "var(--pb-sep)",
            },
          }),
          menu: (base) => ({ ...base, zIndex: 999 }),
          input: (base) => ({ ...base, boxShadow: "none" }),
        }}
/>
```
![image](https://user-images.githubusercontent.com/47362439/195305505-de2c361e-4d90-4fea-8b13-c82a454bdb46.png)

**Comment by hyp3rflow** [comment]
@SimYunSup Seems good 😊! Could you make the pull request?

**Comment by SimYunSup** [comment]
Ok, I'll make Pull Request now.
